"""Initial Migration

Revision ID: 89dfd85e74ba
Revises: 292316ea35b8
Create Date: 2019-02-27 08:41:50.466750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dfd85e74ba'
down_revision = '292316ea35b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pitches')
    # ### end Alembic commands ###
