"""Initial Migration

Revision ID: e2b889641d36
Revises: 8c46d03945d4
Create Date: 2019-02-28 12:33:59.314260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b889641d36'
down_revision = '8c46d03945d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('pitch', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('Description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'description')
    # ### end Alembic commands ###
